"""
schema_introspector.py
----------------------
Utility for introspecting database schemas across all four DAB database types
(PostgreSQL, MongoDB, SQLite, DuckDB) and returning a unified schema description
the agent can inject into its context window.

DAB Failure Categories addressed:
  - Ill-formatted join key mismatch (surfaces format differences between DBs)
  - Multi-database routing failure (identifies which tables/collections exist where)

Usage:
    from utils.schema_introspector import introspect_schema, introspect_all

    # Introspect a single database
    schema = introspect_schema("postgresql", connection_params)

    # Introspect all connected databases and return unified description
    full_schema = introspect_all(connections)

After running, paste the output into kb/domain/yelp_schema.md to fill in
the [ACTION REQUIRED] sections with confirmed column names and key formats.
"""

import json
from typing import Any


# ---------------------------------------------------------------------------
# Type alias for connection parameters
# ---------------------------------------------------------------------------
ConnectionParams = dict[str, Any]


def introspect_schema(db_type: str, params: ConnectionParams) -> dict:
    """
    Introspect the schema of a single database and return a structured description.

    Args:
        db_type:  One of "postgresql", "mongodb", "sqlite", "duckdb".
        params:   Connection parameters dict. Keys depend on db_type:
                  postgresql/sqlite/duckdb: {"host", "port", "database", "user", "password"}
                    or {"db_path"} for file-based databases.
                  mongodb: {"uri", "database"}

    Returns:
        dict with keys:
          "db_type"   — the database type string
          "tables"    — list of table/collection descriptions, each containing:
                        {"name", "columns": [{"name", "type", "sample_values"}]}
          "row_counts" — dict of table_name → approximate row count
          "errors"    — list of any errors encountered during introspection
    """
    introspectors = {
        "postgresql": _introspect_postgres,
        "mongodb":    _introspect_mongo,
        "sqlite":     _introspect_sqlite,
        "duckdb":     _introspect_duckdb,
    }

    fn = introspectors.get(db_type.lower())
    if fn is None:
        return {
            "db_type": db_type,
            "tables": [],
            "row_counts": {},
            "errors": [f"Unknown db_type '{db_type}'. Must be one of: {list(introspectors)}"],
        }

    return fn(params)


def introspect_all(connections: list[dict]) -> dict:
    """
    Introspect all connected databases and return a unified schema description
    suitable for injection into the agent's context window.

    Args:
        connections: List of dicts, each with keys:
                     {"db_type": str, "name": str, "params": ConnectionParams}
                     "name" is a human-readable label (e.g. "yelp_postgres").

    Returns:
        dict with keys:
          "databases"      — list of per-database schema dicts (from introspect_schema)
          "join_key_hints" — list of detected potential join key mismatches across DBs
          "summary"        — human-readable string suitable for KB injection
    """
    results = []
    for conn in connections:
        schema = introspect_schema(conn["db_type"], conn["params"])
        schema["name"] = conn.get("name", conn["db_type"])
        results.append(schema)

    hints = _detect_join_key_mismatches(results)
    summary = _build_summary(results, hints)

    return {
        "databases": results,
        "join_key_hints": hints,
        "summary": summary,
    }


def format_for_kb(introspection_result: dict) -> str:
    """
    Format the output of introspect_all() as a markdown string ready to paste
    into kb/domain/yelp_schema.md or equivalent domain KB document.

    Args:
        introspection_result: Output of introspect_all().

    Returns:
        Markdown-formatted string with confirmed schema details.
    """
    lines = ["# Confirmed Schema (generated by schema_introspector)\n"]
    for db in introspection_result["databases"]:
        lines.append(f"## {db.get('name', db['db_type'])} ({db['db_type']})\n")
        for table in db.get("tables", []):
            lines.append(f"### {table['name']}")
            lines.append(f"Row count: ~{db['row_counts'].get(table['name'], 'unknown')}\n")
            lines.append("| Column | Type | Sample Values |")
            lines.append("|--------|------|---------------|")
            for col in table.get("columns", []):
                samples = ", ".join(str(v) for v in col.get("sample_values", []))
                lines.append(f"| {col['name']} | {col['type']} | {samples} |")
            lines.append("")

    if introspection_result.get("join_key_hints"):
        lines.append("## Detected Join Key Mismatch Hints\n")
        for hint in introspection_result["join_key_hints"]:
            lines.append(f"- {hint}")
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Private per-database introspection stubs
# Drivers: replace the placeholder logic with real DB connections.
# Each function must return the same schema dict structure as introspect_schema().
# ---------------------------------------------------------------------------

def _introspect_postgres(params: ConnectionParams) -> dict:
    """
    Introspect a PostgreSQL database.
    Placeholder — replace with psycopg2 or asyncpg connection.

    Real implementation should:
      1. Connect using params["host"], params["port"], params["database"],
         params["user"], params["password"].
      2. Run: SELECT table_name FROM information_schema.tables
              WHERE table_schema = 'public'
      3. For each table, run: SELECT column_name, data_type
                               FROM information_schema.columns
                               WHERE table_name = %s
      4. For each column, run: SELECT <col> FROM <table> LIMIT 3
         to get sample values (useful for detecting key formats).
      5. Run: SELECT relname, n_live_tup FROM pg_stat_user_tables
         for approximate row counts.
    """
    print("[schema_introspector] PostgreSQL introspection — placeholder. "
          "Replace with real psycopg2 connection.")
    return {
        "db_type": "postgresql",
        "tables": [
            {
                "name": "business",
                "columns": [
                    {"name": "business_id", "type": "integer", "sample_values": [1, 2, 3]},
                    {"name": "name",        "type": "text",    "sample_values": ["Joe's Diner"]},
                    {"name": "city",        "type": "text",    "sample_values": ["Phoenix"]},
                    {"name": "stars",       "type": "float",   "sample_values": [4.5]},
                    {"name": "categories",  "type": "text",    "sample_values": ["Restaurants, Italian"]},
                ]
            },
            {
                "name": "review",
                "columns": [
                    {"name": "review_id",   "type": "integer", "sample_values": [101, 102]},
                    {"name": "user_id",     "type": "integer", "sample_values": [12345]},
                    {"name": "business_id", "type": "integer", "sample_values": [1]},
                    {"name": "stars",       "type": "integer", "sample_values": [5]},
                    {"name": "text",        "type": "text",    "sample_values": ["Great food!"]},
                    {"name": "date",        "type": "date",    "sample_values": ["2025-11-01"]},
                ]
            },
            {
                "name": "user",
                "columns": [
                    {"name": "user_id",       "type": "integer", "sample_values": [12345]},
                    {"name": "name",          "type": "text",    "sample_values": ["Alice"]},
                    {"name": "review_count",  "type": "integer", "sample_values": [42]},
                    {"name": "average_stars", "type": "float",   "sample_values": [3.8]},
                ]
            },
        ],
        "row_counts": {"business": 50000, "review": 1000000, "user": 200000},
        "errors": [],
    }


def _introspect_mongo(params: ConnectionParams) -> dict:
    """
    Introspect a MongoDB database.
    Placeholder — replace with pymongo connection.

    Real implementation should:
      1. Connect using params["uri"], params["database"].
      2. Run db.list_collection_names() to get collections.
      3. For each collection, run collection.find_one() to get a sample document
         and extract field names and types from the sample.
      4. Run collection.estimated_document_count() for row counts.
      5. Sample user_id values specifically to detect prefix format.
    """
    print("[schema_introspector] MongoDB introspection — placeholder. "
          "Replace with real pymongo connection.")
    return {
        "db_type": "mongodb",
        "tables": [
            {
                "name": "reviews",
                "columns": [
                    {"name": "user_id",  "type": "string",  "sample_values": ["USR-12345"]},
                    {"name": "useful",   "type": "integer", "sample_values": [3]},
                    {"name": "funny",    "type": "integer", "sample_values": [1]},
                    {"name": "cool",     "type": "integer", "sample_values": [0]},
                    {"name": "elite",    "type": "array",   "sample_values": [["2023", "2024"]]},
                ]
            },
        ],
        "row_counts": {"reviews": 1000000},
        "errors": [],
    }


def _introspect_sqlite(params: ConnectionParams) -> dict:
    """
    Introspect a SQLite database.
    Placeholder — replace with sqlite3 connection.

    Real implementation should:
      1. Connect using params["db_path"].
      2. Run: SELECT name FROM sqlite_master WHERE type='table'
      3. For each table, run: PRAGMA table_info(<table>)
      4. Run: SELECT COUNT(*) FROM <table> for row counts.
    """
    print("[schema_introspector] SQLite introspection — placeholder. "
          "Replace with real sqlite3 connection.")
    return {
        "db_type": "sqlite",
        "tables": [],
        "row_counts": {},
        "errors": ["Placeholder — connect to actual SQLite db_path to introspect."],
    }


def _introspect_duckdb(params: ConnectionParams) -> dict:
    """
    Introspect a DuckDB database.
    Placeholder — replace with duckdb connection.

    Real implementation should:
      1. Connect using params["db_path"] via duckdb.connect().
      2. Run: SHOW TABLES
      3. For each table, run: DESCRIBE <table>
      4. Run: SELECT COUNT(*) FROM <table> for row counts.
      5. Check for pre-aggregated tables (names ending in _summary, _agg, _daily).
    """
    print("[schema_introspector] DuckDB introspection — placeholder. "
          "Replace with real duckdb connection.")
    return {
        "db_type": "duckdb",
        "tables": [],
        "row_counts": {},
        "errors": ["Placeholder — connect to actual DuckDB db_path to introspect."],
    }


def _detect_join_key_mismatches(db_schemas: list[dict]) -> list[str]:
    """
    Compare column names and sample values across databases to detect
    potential join key format mismatches. Returns human-readable hints.

    Current heuristic: find columns with the same name across databases
    but different types or sample value formats.
    """
    hints = []
    col_index: dict[str, list[dict]] = {}

    for db in db_schemas:
        for table in db.get("tables", []):
            for col in table.get("columns", []):
                key = col["name"]
                col_index.setdefault(key, []).append({
                    "db": db.get("name", db["db_type"]),
                    "table": table["name"],
                    "type": col["type"],
                    "samples": col.get("sample_values", []),
                })

    for col_name, entries in col_index.items():
        if len(entries) < 2:
            continue
        types = {e["type"] for e in entries}
        if len(types) > 1:
            desc = " vs ".join(
                f"{e['db']}.{e['table']}.{col_name} ({e['type']}, "
                f"e.g. {e['samples'][0] if e['samples'] else 'no sample'})"
                for e in entries
            )
            hints.append(f"Potential mismatch on '{col_name}': {desc}")

    return hints


def _build_summary(db_schemas: list[dict], hints: list[str]) -> str:
    lines = ["## Schema Summary (for agent context injection)\n"]
    for db in db_schemas:
        name = db.get("name", db["db_type"])
        tables = [t["name"] for t in db.get("tables", [])]
        lines.append(f"- **{name}** ({db['db_type']}): tables/collections = {tables}")
    if hints:
        lines.append("\n### Join Key Mismatch Hints")
        for h in hints:
            lines.append(f"- {h}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Smoke test
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    connections = [
        {"db_type": "postgresql", "name": "yelp_postgres", "params": {}},
        {"db_type": "mongodb",    "name": "yelp_mongo",    "params": {}},
        {"db_type": "sqlite",     "name": "dab_sqlite",    "params": {}},
        {"db_type": "duckdb",     "name": "dab_duckdb",    "params": {}},
    ]

    result = introspect_all(connections)
    print(format_for_kb(result))
    assert len(result["databases"]) == 4
    assert any("user_id" in h for h in result["join_key_hints"]), \
        "Expected user_id mismatch hint not detected"
    print("\nschema_introspector: smoke test passed.")