"""
schema_introspector.py
----------------------
Utility for introspecting database schemas across all four DAB database types
(PostgreSQL, MongoDB, SQLite, DuckDB) and returning a unified schema description
the agent can inject into its context window.

DAB Failure Categories addressed:
  - Ill-formatted join key mismatch (surfaces format differences between DBs)
  - Multi-database routing failure (identifies which tables/collections exist where)

Usage:
    from utils.schema_introspector import introspect_schema, introspect_all

    # Introspect a single database
    schema = introspect_schema("postgresql", connection_params)

    # Introspect all connected databases and return unified description
    full_schema = introspect_all(connections)

After running, paste the output into kb/domain/yelp_schema.md to fill in
the [ACTION REQUIRED] sections with confirmed column names and key formats.
"""

import json
import sqlite3
from typing import Any

import duckdb
import psycopg2
from pymongo import MongoClient


# ---------------------------------------------------------------------------
# Type alias for connection parameters
# ---------------------------------------------------------------------------
ConnectionParams = dict[str, Any]


def introspect_schema(db_type: str, params: ConnectionParams) -> dict:
    """
    Introspect the schema of a single database and return a structured description.

    Args:
        db_type:  One of "postgresql", "mongodb", "sqlite", "duckdb".
        params:   Connection parameters dict. Keys depend on db_type:
                  postgresql/sqlite/duckdb: {"host", "port", "database", "user", "password"}
                    or {"db_path"} for file-based databases.
                  mongodb: {"uri", "database"}

    Returns:
        dict with keys:
          "db_type"   — the database type string
          "tables"    — list of table/collection descriptions, each containing:
                        {"name", "columns": [{"name", "type", "sample_values"}]}
          "row_counts" — dict of table_name → approximate row count
          "errors"    — list of any errors encountered during introspection
    """
    introspectors = {
        "postgresql": _introspect_postgres,
        "mongodb":    _introspect_mongo,
        "sqlite":     _introspect_sqlite,
        "duckdb":     _introspect_duckdb,
    }

    fn = introspectors.get(db_type.lower())
    if fn is None:
        return {
            "db_type": db_type,
            "tables": [],
            "row_counts": {},
            "errors": [f"Unknown db_type '{db_type}'. Must be one of: {list(introspectors)}"],
        }

    return fn(params)


def introspect_all(connections: list[dict]) -> dict:
    """
    Introspect all connected databases and return a unified schema description
    suitable for injection into the agent's context window.

    Args:
        connections: List of dicts, each with keys:
                     {"db_type": str, "name": str, "params": ConnectionParams}
                     "name" is a human-readable label (e.g. "yelp_postgres").

    Returns:
        dict with keys:
          "databases"      — list of per-database schema dicts (from introspect_schema)
          "join_key_hints" — list of detected potential join key mismatches across DBs
          "summary"        — human-readable string suitable for KB injection
    """
    results = []
    for conn in connections:
        schema = introspect_schema(conn["db_type"], conn["params"])
        schema["name"] = conn.get("name", conn["db_type"])
        results.append(schema)

    hints = _detect_join_key_mismatches(results)
    summary = _build_summary(results, hints)

    return {
        "databases": results,
        "join_key_hints": hints,
        "summary": summary,
    }


def format_for_kb(introspection_result: dict) -> str:
    """
    Format the output of introspect_all() as a markdown string ready to paste
    into kb/domain/yelp_schema.md or equivalent domain KB document.

    Args:
        introspection_result: Output of introspect_all().

    Returns:
        Markdown-formatted string with confirmed schema details.
    """
    lines = ["# Confirmed Schema (generated by schema_introspector)\n"]
    for db in introspection_result["databases"]:
        lines.append(f"## {db.get('name', db['db_type'])} ({db['db_type']})\n")
        for table in db.get("tables", []):
            lines.append(f"### {table['name']}")
            lines.append(f"Row count: ~{db['row_counts'].get(table['name'], 'unknown')}\n")
            lines.append("| Column | Type | Sample Values |")
            lines.append("|--------|------|---------------|")
            for col in table.get("columns", []):
                raw_samples = ", ".join(str(v) for v in col.get("sample_values", []))
                samples = raw_samples[:120] + "..." if len(raw_samples) > 120 else raw_samples
                lines.append(f"| {col['name']} | {col['type']} | {samples} |")
            lines.append("")

    if introspection_result.get("join_key_hints"):
        lines.append("## Detected Join Key Mismatch Hints\n")
        for hint in introspection_result["join_key_hints"]:
            lines.append(f"- {hint}")
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Private per-database introspection stubs
# Drivers: replace the placeholder logic with real DB connections.
# Each function must return the same schema dict structure as introspect_schema().
# ---------------------------------------------------------------------------

def _introspect_postgres(params: ConnectionParams) -> dict:
    tables, row_counts, errors = [], {}, []
    try:
        conn = psycopg2.connect(
            host=params.get("host", "127.0.0.1"),
            port=params.get("port", 5432),
            dbname=params["database"],
            user=params["user"],
            password=params.get("password", ""),
        )
        cur = conn.cursor()
        cur.execute("SELECT table_name FROM information_schema.tables WHERE table_schema='public'")
        table_names = [r[0] for r in cur.fetchall()]
        for tname in table_names:
            cur.execute("SELECT column_name, data_type FROM information_schema.columns WHERE table_name=%s", (tname,))
            cols_raw = cur.fetchall()
            columns = []
            for col_name, col_type in cols_raw:
                try:
                    cur.execute(f'SELECT "{col_name}" FROM "{tname}" LIMIT 3')
                    samples = [r[0] for r in cur.fetchall()]
                except Exception:
                    samples = []
                columns.append({"name": col_name, "type": col_type, "sample_values": samples})
            cur.execute(f'SELECT COUNT(*) FROM "{tname}"')
            row_counts[tname] = cur.fetchone()[0]
            tables.append({"name": tname, "columns": columns})
        conn.close()
    except Exception as e:
        errors.append(str(e))
    return {"db_type": "postgresql", "tables": tables, "row_counts": row_counts, "errors": errors}


def _introspect_mongo(params: ConnectionParams) -> dict:
    tables, row_counts, errors = [], {}, []
    try:
        client = MongoClient(params.get("uri", "mongodb://127.0.0.1:27017"))
        db = client[params["database"]]
        for cname in db.list_collection_names():
            sample_doc = db[cname].find_one()
            columns = []
            if sample_doc:
                for field, value in sample_doc.items():
                    # Sample 3 values for join key format detection
                    samples = [d.get(field) for d in db[cname].find({field: {"$exists": True}}, {field: 1}).limit(3)]
                    columns.append({
                        "name": field,
                        "type": type(value).__name__,
                        "sample_values": [str(s) for s in samples if s is not None],
                    })
            row_counts[cname] = db[cname].estimated_document_count()
            tables.append({"name": cname, "columns": columns})
        client.close()
    except Exception as e:
        errors.append(str(e))
    return {"db_type": "mongodb", "tables": tables, "row_counts": row_counts, "errors": errors}


def _introspect_sqlite(params: ConnectionParams) -> dict:
    tables, row_counts, errors = [], {}, []
    try:
        conn = sqlite3.connect(params["db_path"])
        cur = conn.cursor()
        cur.execute("SELECT name FROM sqlite_master WHERE type='table'")
        table_names = [r[0] for r in cur.fetchall()]
        for tname in table_names:
            cur.execute(f"PRAGMA table_info('{tname}')")
            cols_raw = cur.fetchall()  # (cid, name, type, notnull, dflt, pk)
            columns = []
            for col in cols_raw:
                col_name, col_type = col[1], col[2]
                try:
                    cur.execute(f'SELECT "{col_name}" FROM "{tname}" LIMIT 3')
                    samples = [r[0] for r in cur.fetchall()]
                except Exception:
                    samples = []
                columns.append({"name": col_name, "type": col_type, "sample_values": samples})
            cur.execute(f'SELECT COUNT(*) FROM "{tname}"')
            row_counts[tname] = cur.fetchone()[0]
            tables.append({"name": tname, "columns": columns})
        conn.close()
    except Exception as e:
        errors.append(str(e))
    return {"db_type": "sqlite", "tables": tables, "row_counts": row_counts, "errors": errors}


def _introspect_duckdb(params: ConnectionParams) -> dict:
    tables, row_counts, errors = [], {}, []
    try:
        conn = duckdb.connect(params["db_path"], read_only=True)
        table_names = [r[0] for r in conn.execute("SHOW TABLES").fetchall()]
        for tname in table_names:
            desc = conn.execute(f"DESCRIBE {tname}").fetchall()  # (name, type, null, key, default, extra)
            columns = []
            for col in desc:
                col_name, col_type = col[0], col[1]
                try:
                    samples = [r[0] for r in conn.execute(f'SELECT "{col_name}" FROM "{tname}" LIMIT 3').fetchall()]
                except Exception:
                    samples = []
                columns.append({"name": col_name, "type": col_type, "sample_values": samples})
            row_counts[tname] = conn.execute(f'SELECT COUNT(*) FROM "{tname}"').fetchone()[0]
            tables.append({"name": tname, "columns": columns})
        conn.close()
    except Exception as e:
        errors.append(str(e))
    return {"db_type": "duckdb", "tables": tables, "row_counts": row_counts, "errors": errors}


def _detect_join_key_mismatches(db_schemas: list[dict]) -> list[str]:
    """
    Compare column names and sample values across databases to detect
    potential join key format mismatches. Returns human-readable hints.

    Current heuristic: find columns with the same name across databases
    but different types or sample value formats.
    """
    hints = []
    col_index: dict[str, list[dict]] = {}

    for db in db_schemas:
        for table in db.get("tables", []):
            for col in table.get("columns", []):
                key = col["name"]
                col_index.setdefault(key, []).append({
                    "db": db.get("name", db["db_type"]),
                    "table": table["name"],
                    "type": col["type"],
                    "samples": col.get("sample_values", []),
                })

    for col_name, entries in col_index.items():
        if len(entries) < 2:
            continue
        types = {e["type"] for e in entries}
        if len(types) > 1:
            desc = " vs ".join(
                f"{e['db']}.{e['table']}.{col_name} ({e['type']}, "
                f"e.g. {e['samples'][0] if e['samples'] else 'no sample'})"
                for e in entries
            )
            hints.append(f"Potential mismatch on '{col_name}': {desc}")

    return hints


def _build_summary(db_schemas: list[dict], hints: list[str]) -> str:
    lines = ["## Schema Summary (for agent context injection)\n"]
    for db in db_schemas:
        name = db.get("name", db["db_type"])
        tables = [t["name"] for t in db.get("tables", [])]
        lines.append(f"- **{name}** ({db['db_type']}): tables/collections = {tables}")
    if hints:
        lines.append("\n### Join Key Mismatch Hints")
        for h in hints:
            lines.append(f"- {h}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Smoke test
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    connections = [
        {"db_type": "postgresql", "name": "yelp_postgres", "params": {}},
        {"db_type": "mongodb",    "name": "yelp_mongo",    "params": {}},
        {"db_type": "sqlite",     "name": "dab_sqlite",    "params": {}},
        {"db_type": "duckdb",     "name": "dab_duckdb",    "params": {}},
    ]

    result = introspect_all(connections)
    print(format_for_kb(result))
    assert len(result["databases"]) == 4
    assert any("user_id" in h for h in result["join_key_hints"]), \
        "Expected user_id mismatch hint not detected"
    print("\nschema_introspector: smoke test passed.")